compact: true
quiet: true
download-external-modules: true
evaluate-variables: true
external-modules-download-path: .external_modules
directory:
  - ./
framework:
  - secrets
  - terraform
  - terraform_plan
  - bitbucket_pipelines
  - circleci_pipelines
  - argo_workflows
  - arm
  - bicep
  - cloudformation
  - dockerfile
  - github_configuration
  - github_actions
  - gitlab_configuration
  - gitlab_ci
  - bitbucket_configuration
  - helm
  - json
  - yaml
  - kubernetes
  - kustomize
  - openapi
  - sca_package
  - sca_image
  - serverless
skip-path:
  - "notes/.*"
skip-check:
  - CKV_K8S_15 # "Image Pull Policy should be Always"
  - CKV2_GHA_1 # CodeQL Tweak, TODO Inline Skip
